version: "3.3"
services:
  spa:
    image: isepworkshop21.azurecr.io/workshop-isep-containers_spa:7.0
    build:
      context: ./Spa
    restart: always
    ports: 
      - "80:80"
    depends_on: 
      - backend
  backend:
    image: isepworkshop21.azurecr.io/workshop-isep-containers_dotnet_api:latest
    build:
      context: ./WebApi
    restart: always
    ports:
      - "5000:5000"
    environment: 
      ASPNETCORE_URLS: http://+:5000

